title: Ziao Yang 杨子敖
position: PhD Candidate
affiliation: Brandeis University
email: ziaoyang@beandeis.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=9xV-rmoAAAAJ&hl=zh-CN&oi=ao
github_link: https://github.com/yangziao56
linkedin: https://www.linkedin.com/in/%E5%AD%90%E6%95%96-%E6%9D%A8-a1a13a223/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
